# tests_gtp.cmake -- generated test definitions

add_eth_unit_test(test_param_network
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/features/generic_tx_parser/gtp_param_network.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  DEFS
    HAVE_SPRINTF
  WRAPS
    get_network_as_string_from_chain_id
    add_to_field_table
)

add_eth_unit_test(test_param_trusted_name
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/features/generic_tx_parser/gtp_param_trusted_name.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    get_trusted_name
    get_address_display_name
    get_public_key
    get_current_tx_chain_id
    add_to_field_table
    get_network_as_string_from_chain_id
)

add_eth_unit_test(test_param_raw
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/features/generic_tx_parser/gtp_param_raw.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/utils/utils.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/src/os_printf.c
  DEFS
    HAVE_SPRINTF
    HAVE_SNPRINTF
    HAVE_SNPRINTF_FORMAT_U
  WRAPS
    add_to_field_table
    get_matching_map_entry
)

add_eth_unit_test(test_param_group
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_group.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  WRAPS
    format_field
    handle_field_struct
    verify_field_struct
    cleanup_field
    cleanup_field_constraints
)

add_eth_unit_test(test_param_token_amount
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_token_amount.c
    ${APP_DIR}/features/provide_erc20_token_information/token_info.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/utils/utils.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/src/os_printf.c
    ${BOLOS_SDK}/lib_lists/lists.c
  DEFS
    HAVE_SPRINTF
    HAVE_SNPRINTF
    HAVE_SNPRINTF_FORMAT_U
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    get_current_tx_info
    get_matching_token_info_or_dummy
    add_to_field_table
    get_displayable_ticker
)

add_eth_unit_test(test_param_calldata
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_calldata.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${PLUGIN_DIR}/common_utils.c
  DEFS
    HAVE_SPRINTF
    HAVE_SNPRINTF
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    tx_ctx_init
    calldata_init
    calldata_append
    calldata_delete
)

add_eth_unit_test(test_param_amount
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_amount.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    get_current_tx_info
    get_displayable_ticker
    add_to_field_table
)

add_eth_unit_test(test_param_datetime
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_datetime.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/utils/time_format.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
)

add_eth_unit_test(test_param_duration
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_duration.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
)

add_eth_unit_test(test_param_unit
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_unit.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
)

add_eth_unit_test(test_param_enum
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_enum.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  INCLUDES
    ${APP_DIR}/features/provide_enum_value
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
    get_current_tx_info
    get_current_calldata
    calldata_get_selector
    get_matching_enum
)

add_eth_unit_test(test_param_token
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_token.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/features/provide_erc20_token_information/token_info.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
    get_current_tx_info
    get_matching_token_info_or_dummy
    get_displayable_ticker
)

add_eth_unit_test(test_param_nft
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_param_nft.c
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  INCLUDES
    ${APP_DIR}/features/provide_nft_information
  WRAPS
    value_get
    value_cleanup
    handle_value_struct
    add_to_field_table
    get_current_tx_info
    get_matching_nft_info
)

add_eth_unit_test(test_field_validation
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_field.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${PLUGIN_DIR}/common_utils.c
    ${MOCK_DIR}/field_validation_mocks.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  COMPILE_OPTIONS -fshort-enums
)

add_eth_unit_test(test_field_table
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_field_table.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  INCLUDES
    ${APP_DIR}/features/sign_message_eip712
    ${APP_DIR}/features/provide_trusted_name
)

add_eth_unit_test(test_tx_info
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_tx_info.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/utils/time_format.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  INCLUDES
    ${APP_DIR}/features/provide_proxy_info
    ${APP_DIR}/features/provide_trusted_name
  WRAPS
    hash_nbytes
    finalize_hash
    check_signature_with_pubkey
    get_tx_ctx_count
    calldata_get_selector
)

add_eth_unit_test(test_tx_ctx
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/tx_ctx.c
    ${APP_DIR}/features/generic_tx_parser/calldata.c
    ${APP_DIR}/utils/mem_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  INCLUDES
    ${APP_DIR}/features/provide_proxy_info
    ${APP_DIR}/features/provide_trusted_name
    ${APP_DIR}/features/sign_message_eip712
    ${APP_DIR}/features/get_public_key
  WRAPS
    get_public_key
    get_address_display_name
    finalize_hash
    ui_gcs_cleanup
    delete_tx_info
    field_table_init
    field_table_cleanup
    get_implem_contract
)

add_eth_unit_test(test_data_path
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_data_path.c
    ${APP_DIR}/features/generic_tx_parser/gtp_path_array.c
    ${APP_DIR}/features/generic_tx_parser/gtp_path_slice.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  WRAPS
    get_current_calldata
    calldata_get_chunk
)

add_eth_unit_test(test_value
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/gtp_value.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  INCLUDES
    ${APP_DIR}/features/provide_map_entry
  WRAPS
    data_path_get
    data_path_cleanup
    handle_data_path_struct
    get_current_tx_from
    get_current_tx_to
    get_current_tx_amount
    get_current_tx_info
    get_matching_map_entry
)

add_eth_unit_test(test_provide_map_entry
  APP_SOURCES
    ${APP_DIR}/features/provide_map_entry/map_entry.c
    ${APP_DIR}/tlv_apdu.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/mem_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint256.c
    ${APP_DIR}/uint128.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
    ${BOLOS_SDK}/src/os_printf.c
  WRAPS
    hash_nbytes
    finalize_hash
    check_signature_with_pubkey
    get_current_tx_info
    get_current_calldata
    calldata_get_selector
    get_implem_contract
)

add_eth_unit_test(test_enum_value
  APP_SOURCES
    ${APP_DIR}/features/provide_enum_value/enum_value.c
    ${APP_DIR}/utils/tlv_utils.c
    ${APP_DIR}/utils/utils.c
    ${APP_DIR}/uint128.c
    ${APP_DIR}/uint256.c
    ${PLUGIN_DIR}/common_utils.c
  SDK_SOURCES
    ${BOLOS_SDK}/lib_lists/lists.c
  INCLUDES
    ${APP_DIR}/features/provide_enum_value
    ${APP_DIR}/features/provide_proxy_info
  WRAPS
    check_signature_with_pubkey
    finalize_hash
    hash_nbytes
    get_implem_contract
  COMPILE_OPTIONS "SHELL:-include os_pic.h"
)

add_eth_unit_test(test_cmd_field_tx_info
  APP_SOURCES
    ${APP_DIR}/features/generic_tx_parser/cmd_field.c
    ${APP_DIR}/features/generic_tx_parser/cmd_tx_info.c
  WRAPS
    tlv_from_apdu
    get_current_tx_info
    gcs_cleanup
)

add_eth_unit_test(test_cmd_map_entry
  APP_SOURCES
    ${APP_DIR}/features/provide_map_entry/cmd_map_entry.c
  INCLUDES
    ${APP_DIR}/features/provide_map_entry
  WRAPS
    tlv_from_apdu
)
